### ISSUE TITLE
[Week 04] 이번주 머지는 스쿼시 머지 합니다?

### ISSUE THREAD

**Issue by JeonHyoChang** [CodeSquad-2023-BE-Study/Algorithm-Study#29]
요청사항 있으면 말씀 남겨주세요~~

**Comment by jinny-l** [comment]
스쿼시 머지하기 위해 이번주부터 main이 아닌 브랜치에 커밋했는데
스쿼시 머지하고 그 이후 PR에 이전 커밋 딸려오는지 확인해 봐야 할 것 같아요!

아 그리구 저는 월화중으로 다른 분들 PR 보내주신 거 코드리뷰 한번 하려구요 ㅠㅠ
